// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2uDszfYpwfuZ69jLs39THtAiS8x0DbvU',
    appId: '1:29924222977:web:bf9fe9aa9d5a5d7a27f800',
    messagingSenderId: '29924222977',
    projectId: 'rpl-uas-21900',
    authDomain: 'rpl-uas-21900.firebaseapp.com',
    storageBucket: 'rpl-uas-21900.appspot.com',
    measurementId: 'G-XSMZH3QTZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCORy_CfzmbU_xhAGG4WXOvzZuFBrIIWRA',
    appId: '1:29924222977:android:d97c595e2ff5385b27f800',
    messagingSenderId: '29924222977',
    projectId: 'rpl-uas-21900',
    storageBucket: 'rpl-uas-21900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4ZXDAERc1r_JafOQxNGb0-EYzZtZyew',
    appId: '1:29924222977:ios:cdd57f69d292dde927f800',
    messagingSenderId: '29924222977',
    projectId: 'rpl-uas-21900',
    storageBucket: 'rpl-uas-21900.appspot.com',
    iosBundleId: 'com.example.tubesRplUpdate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb4ZXDAERc1r_JafOQxNGb0-EYzZtZyew',
    appId: '1:29924222977:ios:88ca3bda8290269427f800',
    messagingSenderId: '29924222977',
    projectId: 'rpl-uas-21900',
    storageBucket: 'rpl-uas-21900.appspot.com',
    iosBundleId: 'com.example.tubesRplUpdate.RunnerTests',
  );
}
